---
settings:
  name: Licenses and subscriptions
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentação de licenças e assinaturas
    url: "/index.html"
  - title: Notas de lançamento
    entries:
    - title: O que há de novo
      url: "/whats-new.html"
  - title: Começar
    entries:
    - title: Aprenda sobre
      url: "/concept-digital-wallet.html"
  - title: Licenças de uso e assinaturas
    entries:
    - title: Use o painel Visão geral
      url: "/task-homepage.html"
    - title: Gerenciar licenças
      entries:
      - title: Gerenciar licenças diretas
        url: "/task-manage-data-services-licenses.html"
      - title: Gerenciar licenças para Cloud Volumes ONTAP
        entries:
        - title: Licenças baseadas em capacidade para Cloud Volumes ONTAP
          url: "/task-manage-capacity-licenses.html"
        - title: Licenças baseadas em nó para Cloud Volumes ONTAP
          url: "/task-manage-node-based-licenses.html"
    - title: Gerenciar ofertas privadas
      entries:
      - title: Gerenciar uma oferta privada da AWS
        url: "/task-manage-private-aws.html"
      - title: Gerenciar uma oferta privada do Azure
        url: "/task-manage-private-azure.html"
      - title: Gerenciar uma oferta privada do Google Cloud
        url: "/task-manage-private-google-cloud.html"
    - title: Gerenciar assinaturas do Marketplace
      url: "/task-manage-subscriptions.html"
    - title: Gerenciar assinaturas do Keystone
      url: "/task-manage-keystone.html"
    - title: Conhecimento e suporte
      entries:
      - title: Registre-se para obter suporte
        url: "/task-support-registration.html"
      - title: Obter ajuda
        url: "/task-get-help.html"
    - title: Avisos legais
      url: "/legal-notices.html"
product-family:
  name: NetApp Console
  repo: console-family
