---
sidebar: sidebar 
permalink: task-manage-private-aws.html 
keywords: activate, license, licensing, install, request capacity, link subscription, keystone flex, bluexp, netapp console, marketplace, aws 
summary: Aceite uma oferta privada do Marketplace para o NetApp Console no Portal do AWS Marketplace e configure as credenciais da AWS no Console. 
---
= Aceitar e configurar uma oferta privada do AWS Marketplace para o NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Aceite uma oferta privada do Marketplace para o NetApp Console no Portal do AWS Marketplace e configure as credenciais da AWS no Console.

.Antes de começar
* Trabalhe com as vendas da NetApp para criar uma oferta privada e obter o link de ativação.
* Certifique-se de ter as permissões necessárias do AWS Marketplace:
+
** link:https://docs.aws.amazon.com/marketplace/latest/buyerguide/buyer-private-offers-subscribing.html["Visualizar e assinar uma oferta privada"]
** link:https://docs.aws.amazon.com/marketplace/latest/buyerguide/buyer-iam-users-groups-policies.html["Validação de permissões do comprador"]






== Aceite a oferta privada no portal do AWS Marketplace

É necessário concluir a atribuição da assinatura no Console para ativar a compra e aplicar o preço com desconto.


NOTE: Você precisa concluir todas as etapas para ativar sua oferta exclusiva. Ignorar etapas pode resultar em erros de cobrança. Aceitar e ativar a oferta várias vezes pode resultar em cobrança duplicada.

.Passos
. Selecione o link de ativação da oferta privada fornecido pela sua equipe de vendas da NetApp.
+
O link deve ser semelhante ao seguinte: `https://aws.amazon.com/marketplace/saas/ordering?productId=aaa&offerId=offer-aaa`

+
Caso não tenha recebido o link, visualize as ofertas privadas no console do AWS Marketplace. As seguintes permissões são necessárias:

+
** Usando políticas gerenciadas pela AWS: *AWSMarketplaceRead-only*, *AWSMarketplaceManageSubscriptions* ou *AWSMarketplaceFullAccess*
** Usando políticas de IAM personalizadas: `aws-marketplace:ListPrivateListings` e `aws-marketplace:ViewSubscriptions`


. Você será redirecionado ao AWS Marketplace para visualizar a oferta privada.
+

NOTE: Ofertas privadas são criadas com base em listagens públicas. Use o menu suspenso *Seleção de oferta* para alternar entre ofertas públicas e privadas.

. Revise os detalhes da oferta privada e confirme se eles correspondem ao seu acordo. Se estiverem incorretas, não aceite. Entre em contato com sua equipe de contas da NetApp .
+
[NOTE]
====
Existem dois tipos de ofertas privadas:

** *Uso sob demanda*
+
*** Informações sobre preços
*** Termos legais


** *Contrato*
+
*** Duração e datas
*** Configurações de renovação
*** Opções de contrato
*** Preço total do contrato




Para ofertas de contrato, insira o número de unidades acordadas. Para o Cloud Volumes ONTAP, certifique-se de selecionar a licença correta antes de assinar.

====
. Para aceitar a oferta privada, faça o seguinte:
+
.. Para uso sob demanda, selecione *Assinar*.
.. Para propostas contratuais, insira o número de unidades para cada serviço e selecione *Criar contrato*.


. Após a aceitação, um banner confirma a inscrição e fornece instruções de registro.
. Selecione *Configurar sua conta*. Isso redireciona para o NetApp Console para configurar a assinatura.
+
[NOTE]
====
Se você aceitou a oferta, mas não concluiu o cadastro, retorne à página do produto. Para anúncios com contrato, selecione *Ver opções de compra* para exibir a oferta e, em seguida, selecione *Configurar sua conta*.

====
. Sign in em https://console.netapp.com[].
. Após efetuar login, navegue até https://console.netapp.com/licenses/overview[] . Você será solicitado a:
+
.. Insira um *Nome de exibição* para a assinatura do Marketplace.
.. Selecione a *Organization* do NetApp Console com acesso à assinatura.
.. [Opcional] Ative *Substituir assinatura existente* para sobrescrever uma assinatura existente para uma organização.
+
[NOTE]
====
*** A substituição se aplica somente a uma conta do Console.
*** Para associar várias contas à mesma assinatura, configure contas adicionais manualmente.
*** Se as credenciais nunca foram associadas a uma assinatura, associe-as manualmente, conforme descrito na próxima seção.


====


. Selecione **Associate**.
. Preencha o formulário para associar a assinatura à sua organização do Console. Selecione **Associar**.
. Após associar a assinatura, selecione a guia **Preferências de faturamento**.
. Analise as opções de assinatura do marketplace.
. Selecione a assinatura do marketplace que deseja faturar.  Isso só se aplica quando há mais de uma opção.
. Selecione **Salvar alterações**.
. Repita esses passos conforme necessário, caso haja várias assinaturas em diferentes provedores de nuvem.


Para obter mais informações sobre assinaturas de marketplace e faturamento direto de licenças, consulte o link:https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["Documentação de preferências de faturamento"].
