---
sidebar: sidebar 
permalink: task-manage-data-services-licenses.html 
keywords: data services, byol, cloud backup, cloud tiering, data sense, cloud data sense, obtain license file, nlf, add license, update license, bluexp, netapp console, classification, tiering, backup and recovery, disaster recovery 
summary: 'Gerencie licenças que você comprou diretamente da NetApp (BYOL) para uso com serviços de dados da NetApp .  Você pode visualizar a capacidade de licença usada, quanta capacidade livre ainda resta e verá notificações se atingir o limite de capacidade ou a data de expiração.' 
---
= Gerenciar licenças para serviços de dados NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode gerenciar licenças adquiridas diretamente da NetApp (BYOL) para uso com serviços de dados da NetApp , incluindo o Cloud Volumes ONTAP.  Você pode visualizar a capacidade de licença usada, quanta capacidade livre ainda resta e verá notificações quando atingir o limite de capacidade ou a data de expiração.


NOTE: A página *Licenças diretas* lista todas as licenças.  Se você quiser detalhes da licença para um serviço de dados específico, use os blocos de serviço de dados no painel *Visão geral*. link:task-homepage.html#overview-page["Saiba mais sobre o painel Visão geral"] .

As instruções nesta página fornecem informações que se aplicam a cada serviço.  Para obter informações mais específicas sobre o licenciamento desses serviços, consulte as seguintes páginas:

* https://docs.netapp.com/us-en/bluexp-backup-recovery/br-start-licensing.html["Configurar licenciamento para BlueXP backup and recovery"^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["Configurar licenciamento para BlueXP disaster recovery"^]
* https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-licenses.html["Configurar licenciamento para BlueXP ransomware protection"^]
* https://docs.netapp.com/us-en/bluexp-tiering/task-licensing-cloud-tiering.html["Configurar licenciamento para BlueXP tiering"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Configurar licenciamento para o Cloud Volumes ONTAP"^]




== Obter um arquivo de licença

Diretiva não resolvida em <stdin> - include::_include/task-obtain-license.adoc[]



== Adicionar uma licença

Diretiva não resolvida em <stdin> - include::_include/task-add-license.adoc[]



== Atualizar uma licença

Diretiva não resolvida em <stdin> - include::_include/task-update-license.adoc[]



== Ver status da licença

Diretiva não resolvida em <stdin> - include::_include/task-view-license-status.adoc[]
